### ISSUE TITLE
[BUG] Specific cookie doesn't get deleted even though log says it was

### ISSUE THREAD

**Issue by hachel** [mrdokenny/Cookie-AutoDelete#719]
### Describe the Bug/Feature
I have the problem, that a specific cookie doesn't get deleted, even though the log (and the little popup when I close a tab) says it was deleted. The url in question is _portal.bizagi.com_.

Whenever I close a tab, after 15s the little popup shows all the cookies that specific tab had set and which have now been deleted, which is the expected way. But it always includes a cookie from portal.bizagi.com. And when I check in firefox settings there is still a cookie from portal.bizagi.com. All other non gray/whitelisted cookies have been deleted.

The log also says the cookie has been deleted (see below). It is also always the exact same cookie (there seems to be some type of session id in the cookie, see below)

The FAQ said I should manually clear all cookies when some cookies don't get deleted. I deleted the cookie manually twice, but after I visit the site the cookie persists again.

### Screenshot in which the bug can be seen
Popup in german listing the cookies which have been deleted, after I closed a tab where I only visited google.com:

![popup](https://user-images.githubusercontent.com/7252437/81336653-002cd680-90aa-11ea-8652-a96ec9545b74.png)

Log in german saying the bizagi-cookie has been cleaned up because it was not on any white/graylist, after I closed a tab where I only visited google.com (the line concerning bizagi is in every log entry):

![log](https://user-images.githubusercontent.com/7252437/81336667-0458f400-90aa-11ea-89a3-27364fa49c95.png)

### Steps for anyone to reproduce the bug
-

### Your settings 

- OS/version: Windows 10 Enterprise
- Browser/version: Firefox 75
- Cookie AutoDelete version: 3.2.0 

Thank you for your help

**Comment by kennethtran93** [comment]
If you're comfortable with testing the next version, use/install Firefox Developer Edition, go to `about:config` and set `xpinstall.signatures.required` to `false`.  Following that then you can go to `about:addons`, then click on the gear cog and `Install Addon From File`.  See if this works. There's also a debug mode in there but you'll need to access the console via `about:debugging#/runtime/this-firefox` and clicking `Inspect` next to the extension.

**Comment by kennethtran93** [comment]
Also I believe the current Firefox browser is 76.  See if updating to that may help.

**Comment by kennethtran93** [comment]
Could you attach screenshots of the Storage Inspector - the one that lists localstorage, cookies, etc.

**Comment by hachel** [comment]
Hi, thanks for your reply.

Here is a screenshot of the storage inspector. I had to login with a disposable e-mail
 to get the storage inspector to show the offending cookie. I'll try with developer edition of FF next.

![cookie_storage_insp](https://user-images.githubusercontent.com/7252437/81434825-1482d900-9167-11ea-9ce0-3ce43400b665.png)


EDIT: Sorry if I'm blind or stupid, where do I find the next version? On github I only find 3.2.0.

**Comment by kennethtran93** [comment]
Sorry, I forgot to link #713 
Also for the screenshot could I also get the panel on the left side - the one with the headers and domains.

**Comment by kennethtran93** [comment]
Seeing that you're on firefox could you screenshot me the cookies and site date panel?

**Comment by hachel** [comment]
I tried v3.999.999, still the same issue.
Basically to reproduce, go to portal.bizagi.com and login (create account first).

I'm not sure which site panel you mean. This?
![sidepanel](https://user-images.githubusercontent.com/7252437/81562787-b7b93580-9395-11ea-9489-1d6b66888690.png)
(I have some adblockers running, so without them in addition to portal.bizagi.com there is also vars.hotjar.com)

**Comment by kennethtran93** [comment]
Can you enable debug mode using #722 (upcoming version), then rerun your tests and see if you can copy-paste the debug info to a text file and upload it here for me?

**Comment by kennethtran93** [comment]
I've fixed a few things since then.  Try this: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.3.0-alpha1  and send me debug logs please and your settings.

**Comment by kennethtran93** [comment]
With debug mode officially released, what's the current status on the site with the latest version 3.3.1?

**Comment by hachel** [comment]
Hi, 
I've installed 3.3.1 in Firefox Dev. Still the same problem. Here is the log:
[console-export-2020-5-26_17-26-35.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/4683237/console-export-2020-5-26_17-26-35.txt)

What I've done:
1. Clear Log
2. Open new Tab
3. Browse to portal.bizagi.com
4. Log in
5. Close Tab
6. Export Log

Thanks

**Comment by kennethtran93** [comment]
Quick question - do you have firstPartyIsolation turned on?

**Comment by hachel** [comment]
No, right now for testing I'm using a clean Firefox Dev with just CAD installed.

On my regular FF I also don't have that installed.

**Comment by kennethtran93** [comment]
I can reproduce it as well.

I suspect it is because of the path having a `?` in it.  I'm going to spin up a minimal extension testcase and see if manually setting the cookie then removing it after would do it.  If not I'll raise a bug through bugzilla as it is most likely something on their end...that or they will tell me what to do next.

**Comment by kennethtran93** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1641022

**Comment by kennethtran93** [comment]
I suspect that portal.bizagi.com's wordpress cookie did not set the path properly...

**Comment by atomGit** [comment]
post deleted - didn't belong in this issue

**Comment by kennethtran93** [comment]
@atomGit If the cookie count for that website is zero then it doesn't belong here.  This may be related to a recent issue #851 (possibly #845 but Firefox has yet to implement support for those or is undocumented).

**Comment by klausenbusk** [comment]
I have the same issue in Firefox Nightly. At the moment I have 96 cookies which isn't deleted. I'm wondering if this could explain it:
![image](https://user-images.githubusercontent.com/1080056/94347134-1247eb00-0032-11eb-8230-071175b66b3c.png)

**Comment by kennethtran93** [comment]
@klausenbusk
> I have the same issue in Firefox Nightly. At the moment I have 96 cookies which isn't deleted. I'm wondering if this could explain it:
> ![image](https://user-images.githubusercontent.com/1080056/94347134-1247eb00-0032-11eb-8230-071175b66b3c.png)

Neither is related to CAD.
- The first one I believe relates to a DevTools panel (we don't add any devtools items ourselves).
- The second one is from this extension: https://addons.mozilla.org/en-CA/firefox/addon/clearurls/

**Comment by klausenbusk** [comment]
> Neither is related to CAD.

Oh, I though devtools did some sort of filtering, that isn't the case I see. I there anyway I can help debugging why Cookie AutoDelete isn't deleting the cookies?

**Comment by kennethtran93** [comment]
> Oh, I though devtools did some sort of filtering, that isn't the case I see. I there anyway I can help debugging why Cookie AutoDelete isn't deleting the cookies?

Utilize the debug mode in CAD and follow its instructions.  Then navigate as usual and see what the extension logs say.  These logs only persist up until browser restart.

**Comment by klausenbusk** [comment]
Can I share the log in private?

**Comment by kennethtran93** [comment]
Upload files here to me here: https://www.dropbox.com/request/5PSgkPStjFtcIffruEPL.  This requests will close on Sept 30th midnight PST.

In a separate text file, also put in what cookies/domains were kept (and in which container if used) that should have been removed.  Screenshots can also go here as well.

**Comment by klausenbusk** [comment]
> This requests will close on Sept 30th midnight PST.

I have uploaded some files. Please say if you need anything else! :)

**Comment by kennethtran93** [comment]
Thanks.  Due to the experimental state of Nightly it is not officially supported, but I will see if it persists on the general Firefox and the Developer Edition of Firefox.

**Comment by klausenbusk** [comment]
I just looked further in to this.

I checked a few of the cookies manually (`await browser.cookies.getAll({storeId: "firefox-default"})`) and the cookies I checked has all expired. So I think we are hit by [bug 1388873](https://bugzilla.mozilla.org/show_bug.cgi?id=1388873) and `browser.cookies.remove(...)` can't remove expired cookies (it seems). `await browser.cookies.getAll({domain: "<domain>"})` does not include the stale cookies, so something must be broken in Firefox.

**Comment by klausenbusk** [comment]
> So I think we are hit by [bug 1388873](https://bugzilla.mozilla.org/show_bug.cgi?id=1388873) and `browser.cookies.remove(...)` can't remove expired cookies (it seems)

[`browser.cookie.remove(...)`](https://searchfox.org/mozilla-central/rev/7ef5cefd0468b8f509efe38e0212de2398f4c8b3/toolkit/components/extensions/parent/ext-cookies.js#497) -> [`CookieService::Remove`](https://searchfox.org/mozilla-central/source/netwerk/cookie/CookieService.cpp#777) -> [`CookieStorage::RemoveCookie`](https://searchfox.org/mozilla-central/rev/7ef5cefd0468b8f509efe38e0212de2398f4c8b3/netwerk/cookie/CookieStorage.cpp#276) -> [`CookieStorage::FindCookie`](https://searchfox.org/mozilla-central/rev/7ef5cefd0468b8f509efe38e0212de2398f4c8b3/netwerk/cookie/CookieStorage.cpp#168)

`CookieStorage::FindCookie` does not return expired cookies according to the comment, but I'm not sure how it is implemented.

**Comment by kennethtran93** [comment]
> `browser.cookies.remove(...)` can't remove expired cookies (it seems).

Thank you very much for looking into this.  It seems this is very much the culprit of things.  I'll make it so that the expired cookies aren't part of the cleanup logs.  Not sure about Chrome so I'll leave the cleanup options in there but hide it from the cleanup logs.


> `await browser.cookies.getAll({domain: "<domain>"})` does not include the stale cookies

In the cleaning end we query all cookies through its container, so e.g. `browser.cookies.getAll({storeId: "firefox-default"});`  Only though the popup counter does it query by domain.

In a sense this is because cookies sent to host/page only contains non-expired cookies.  Think they need to implement an optional parameter that allows to fetch expired ones to remove.


As a sidenote, we use `Promise.all` in the removal of a batch of cookies, and we don't check if any errors are returned.  Perhaps in the future when `Promise.allSettled` is somehow added to Firefox Android I can actually deal with the resolved (removed) and rejected (not removed/not found/error) cookies responses.

EDIT:  may be able to reset the expired cookies to a session cookie before removing it.

**Comment by klausenbusk** [comment]
I had a further look into this and "first-party Isolation" (thanks @Lusito for the [hint](https://bugzilla.mozilla.org/show_bug.cgi?id=1388873#c6)). Firefox supports ["Dynamic First Party Isolation"](https://www.ghacks.net/2020/04/17/mozilla-adds-dynamic-first-party-isolation-option-to-firefox-77/) and it is enabled in my case.

I sat `firstPartyDomain: null` and it now returns the cookies:
> If you do this, then cookies with any value for firstPartyDomain, as well as cookies which do not have firstPartyDomain set at all, will be included in the results.
```js
$ await browser.cookies.getAll({domain: "store.steampowered.com", firstPartyDomain: null})
Array(5) [ {…}, {…}, {…}, {…}, {…} ]
```
I still can't remove the cookie though:
```js
$ await browser.cookies.remove({"firstPartyDomain": null, "storeId": "firefox-default", "name": "steamCountry", "url": "https://store.steampowered.com/"})
null
```

**Comment by ts1a** [comment]
May be related: https://bugzilla.mozilla.org/show_bug.cgi?id=1556212

**Comment by kennethtran93** [comment]
> @klausenbusk 
> I had a further look into this and "first-party Isolation" (thanks @Lusito for the [hint](https://bugzilla.mozilla.org/show_bug.cgi?id=1388873#c6)). Firefox supports ["Dynamic First Party Isolation"](https://www.ghacks.net/2020/04/17/mozilla-adds-dynamic-first-party-isolation-option-to-firefox-77/) and it is enabled in my case.
> 
> I sat `firstPartyDomain: null` and it now returns the cookies:
> 
> > If you do this, then cookies with any value for firstPartyDomain, as well as cookies which do not have firstPartyDomain set at all, will be included in the results.
> 
> ```js
> $ await browser.cookies.getAll({domain: "store.steampowered.com", firstPartyDomain: null})
> Array(5) [ {…}, {…}, {…}, {…}, {…} ]
> ```
> 
> I still can't remove the cookie though:
> 
> ```js
> $ await browser.cookies.remove({"firstPartyDomain": null, "storeId": "firefox-default", "name": "steamCountry", "url": "https://store.steampowered.com/"})
> null
> ```

We already do this.  The `null` value only applies to the query `getAll` to get all cookies from the domain.  However, when removing cookies, you NEED the actual firstPartyDomain value, which we already cover as we pass in as taken directly from the query result.  In addition, there was a recent browser enhancement for a different FPI value when enabling `privacy.firstparty.isolate.use_site`.

@ts1a 
> 
> 
> May be related: https://bugzilla.mozilla.org/show_bug.cgi?id=1556212

After looking at that report I find no relevance to this.  What you have given is when site cookies cannot be created due to a certain configuration, and a possibility of webextension breaking if webextension uses local SQLite DB and browser FPI.  We don't use SQLite DB as far as I'm concerned.  We store data via browser internal localStorage for webextensions (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local).  As for the FPI portion, it comes from the query mentioned above.

Appreciate the effort though.

**Comment by klausenbusk** [comment]
> We already do this. The `null` value only applies to the query `getAll` to get all cookies from the domain. However, when removing cookies, you NEED the actual firstPartyDomain value, which we already cover as we pass in as taken directly from the query result. In addition, there was a recent browser enhancement for a different FPI value when enabling `privacy.firstparty.isolate.use_site`.

`getAll` returns this cookie:
```json
{
  "name": "steamCountry",
  "value": "XX",
  "domain": "store.steampowered.com",
  "hostOnly": true,
  "path": "/",
  "secure": true,
  "httpOnly": false,
  "sameSite": "no_restriction",
  "session": true,
  "firstPartyDomain": "",
  "storeId": "firefox-default"
}
```
Using the same `firstPartyDomain` value doesn't change anything:
```js
$ await browser.cookies.remove({"firstPartyDomain": "", "storeId": "firefox-default", "name": "steamCountry", "url": "https://store.steampowered.com/"})
null
```
Is this a Firefox bug or what is going on?

**Comment by klausenbusk** [comment]
> Is this a Firefox bug or what is going on?

Oh, a new bug was just created: https://bugzilla.mozilla.org/show_bug.cgi?id=1669716

**Comment by Dealz-416LS** [comment]
Experiencing the same issue, with dFPI enabled if I visit site A, then close the tab I’ll get a notification with cookies deleted for site A, then every time I close a tab I’ll get a notification that mentions cookies were deleted for site A even though I’ve not revisited site A. 

Website cookies get stuck, unable to be deleted by the add-on.

**Comment by kennethtran93** [comment]
According to the Bugzilla report above, dFPI is still an issue for Webextension. I haven't had a chance to see what I can do as a workaround yet.

**Comment by Dealz-416LS** [comment]
@kennethtran93 I noticed this today [Firefox 86: strict enhanced tracking protection w/ dFPI](https://reddit.com/r/firefox/comments/lnpns6/firefox_86_strict_enhanced_tracking_protection/) and was wondering how this will interact with Cookie AutoDelete? 

The dFPI I used was turned on via about:config in 85, I assume the dFPI coming in 86 turned on via Firefox settings will have the same issue with Webextensions so won’t be compatible?

Edit: Total Cookie Protection (Strict mode) produces the same issue.

**Comment by kennethtran93** [comment]
Moving forward, please keep any dFPI related issues to #807.  This issue was originally a separate issue entirely.
